# Generated by Django 5.0.3 on 2024-09-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_options_remove_archivedpost_post_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedpost',
            options={'verbose_name': 'archived post', 'verbose_name_plural': 'archived posts'},
        ),
        migrations.AlterModelTable(
            name='archivedpost',
            table='archived_post',
        ),
    ]
