# Generated by Django 5.0.3 on 2024-09-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_archivedpost_options_alter_archivedpost_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedPost',
        ),
    ]
