# Generated by Django 5.0.3 on 2024-08-23 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio_alter_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', '-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_usernam_b79065_idx',
            old_name='users_user_usernam_65d164_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_email_7bbb4c_idx',
            old_name='users_user_email_6f2530_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
