# Generated by Django 5.0.3 on 2024-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='karma',
        ),
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0, help_text='Karma is a point system that rewards users for their contributions.', verbose_name='karma'),
        ),
    ]
