# Generated by Django 5.0.3 on 2024-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_karma_profile_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='O', max_length=32, verbose_name='gender'),
            preserve_default=False,
        ),
    ]
