# Generated by Django 5.0.3 on 2024-08-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_groups_user_last_seen_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
