# Generated by Django 5.0.3 on 2024-08-23 02:22

import core.utils.validators.phone_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, help_text='A short description about yourself.', max_length=255, verbose_name='bio')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='date of birth')),
                ('nationality', models.CharField(blank=True, max_length=255, verbose_name='nationality')),
                ('phone', models.CharField(blank=True, max_length=32, validators=[core.utils.validators.phone_validator.PhoneValidator], verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', '-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0, help_text='Karma is a point system that rewards users for their contributions.', verbose_name='karma'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
